# Generated by Django 3.2.5 on 2024-04-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createmessage',
            old_name='nameSurname',
            new_name='username',
        ),
    ]
